print("Para calcular a área de um triângulo insira os seguintes valores:")
Base=float(input("Base do Triângulo: "))
Altura=float(input("Altura do Triângulo: "))
area=float((Base*Altura)/2)
print("Área = {}".format(area))
